-- Add Users

INSERT INTO "user" ("username", "email", "password")
VALUES
('john_doe', 'john.doe@example.com', 'password123'),
('jane_smith', 'jane.smith@example.com', 'password123'),
('mike_jones', 'mike.jones@example.com', 'password123'),
('sarah_connor', 'sarah.connor@example.com', 'password123'),
('alex_turner', 'alex.turner@example.com', 'password123'),
('emma_watson', 'emma.watson@example.com', 'password123'),
('liam_garcia', 'liam.garcia@example.com', 'password123'),
('sophia_martinez', 'sophia.martinez@example.com', 'password123'),
('noah_rodriguez', 'noah.rodriguez@example.com', 'password123'),
('olivia_hernandez', 'olivia.hernandez@example.com', 'password123'),
('william_wilson', 'william.wilson@example.com', 'password123'),
('ava_anderson', 'ava.anderson@example.com', 'password123'),
('james_thomas', 'james.thomas@example.com', 'password123'),
('isabella_taylor', 'isabella.taylor@example.com', 'password123'),
('logan_moore', 'logan.moore@example.com', 'password123'),
('mia_jackson', 'mia.jackson@example.com', 'password123'),
('benjamin_white', 'benjamin.white@example.com', 'password123'),
('charlotte_harris', 'charlotte.harris@example.com', 'password123'),
('lucas_clark', 'lucas.clark@example.com', 'password123'),
('amelia_lewis', 'amelia.lewis@example.com', 'password123');


-- Add project

INSERT INTO "project" ("name", "description", "start_date")
VALUES
('EcoTrack', 'Plateforme de suivi carbone pour entreprises', '2023-01-15'),
('HealthGuard', 'Système de monitoring santé connecté', '2023-02-01'),
('CodeFlow', 'Outil collaboratif de développement Agile', '2023-03-10'),
('EduConnect', 'Portail éducatif pour écoles primaires', '2023-04-22'),
('GreenRoute', 'Optimisation de trajets écologiques', '2023-05-05'),
('SmartFarm', 'Solution IoT pour agriculture de précision', '2023-06-18'),
('FinSecure', 'Application bancaire sécurisée', '2023-07-09'),
('ArtVerse', 'Galerie virtuelle pour artistes émergents', '2023-08-12'),
('TravelMate', 'Planificateur de voyages intelligent', '2023-09-25'),
('SportSync', 'Plateforme sociale pour sportifs amateurs', '2023-10-30'),
('EventMaster', 'Gestionnaire d''événements en temps réel', '2023-11-11'),
('FoodSavior', 'Lutte contre le gaspillage alimentaire', '2023-12-01'),
('PetCare+', 'Suivi santé pour animaux domestiques', '2024-01-08'),
('RenewGrid', 'Gestion énergies renouvelables', '2024-02-14'),
('BuildSmart', 'ERP pour chantiers de construction', '2024-03-19'),
('MindSpace', 'Application de méditation guidée', '2024-04-03'),
('RetailAI', 'Optimisation stocks par intelligence artificielle', '2024-05-27'),
('SafeRoute', 'Cartographie sécurisée pour piétons', '2024-06-09'),
('SkillSwap', 'Marché d''échange de compétences', '2024-07-15'),
('UrbanGrow', 'Jardins urbains connectés', '2024-08-22');


-- Add task
INSERT INTO "task" ("name", "description", "priority", "due_date", "status", "project_id")
VALUES
('Implémentation API', 'Développer les endpoints utilisateurs', 2, '2023-02-28', 'In Progress', 1),
('Design UI Dashboard', 'Créer maquettes Figma pour l''espace admin', 3, '2023-03-15', 'To Do', 1),
('Setup CI/CD', 'Configurer pipeline Jenkins/GitHub Actions', 1, '2023-02-10', 'Done', 2),
('Analyse marché', 'Étude concurrentielle secteur santé', 4, '2023-04-01', 'In Progress', 3),
('Refactoring legacy code', 'Nettoyage codebase principale', 2, '2023-05-20', 'To Do', 5),
('Tests de performance', 'Load testing avec JMeter', 1, '2023-06-30', 'To Do', 4),
('Intégration Stripe', 'Paiements sécurisés pour abonnements', 3, '2023-07-15', 'In Progress', 6),
('Migration base de données', 'Passage de MySQL à PostgreSQL', 2, '2023-08-01', 'Done', 7),
('SEO technique', 'Optimisation balises méta et sitemap', 4, '2023-09-10', 'To Do', 8),
('Déploiement AWS', 'Configuration infrastructure EC2/RDS', 1, '2023-10-05', 'In Progress', 9),
('Création contenu marketing', 'Rédaction articles de blog', 3, '2023-11-20', 'To Do', 10),
('Monitoring application', 'Mise en place New Relic', 2, '2023-12-01', 'Done', 11),
('Formation équipe', 'Session sur les bonnes pratiques DevOps', 4, '2024-01-15', 'To Do', 12),
('Audit sécurité', 'Vérification vulnérabilités OWASP', 1, '2024-02-28', 'In Progress', 13),
('Intégration continue', 'Automatisation des tests unitaires', 2, '2024-03-10', 'To Do', 14),
('Optimisation BDD', 'Indexation des requêtes lentes', 3, '2024-04-05', 'Done', 15),
('Développement feature X', 'Implémentation selon spec #245', 2, '2024-05-20', 'In Progress', 16),
('Revue code peer-to-peer', 'Validation PR #134 à #142', 4, '2024-06-01', 'To Do', 17),
('Mise à jour dépendances', 'Upgrade Spring Boot 3.2', 1, '2024-07-15', 'In Progress', 18),
('Création documentation', 'Redaction guide utilisateur final', 3, '2024-08-01', 'To Do', 19),
('Gestion des erreurs', 'Implémentation système de logging', 2, '2024-09-10', 'Done', 20),
('Intégration OAuth2', 'Authentification via Google/Facebook', 1, '2024-10-05', 'To Do', 1),
('Refonte navigation mobile', 'Amélioration UX sur mobile', 3, '2024-11-20', 'In Progress', 2),
('Benchmark solutions', 'Comparatif outils CI/CD', 4, '2024-12-01', 'To Do', 3),
('Optimisation assets', 'Compression images/JS/CSS', 2, '2025-01-15', 'Done', 4),
('Gestion des permissions', 'Implémentation RBAC', 1, '2025-02-28', 'In Progress', 5),
('Internationalisation', 'Support multilingue (en/es/de)', 3, '2025-03-10', 'To Do', 6),
('Alerting système', 'Configuration Prometheus/Grafana', 2, '2025-04-05', 'In Progress', 7),
('Tests e2e', 'Automatisation avec Cypress', 4, '2025-05-20', 'To Do', 8),
('Analyse données utilisateurs', 'Tableau de bord Mixpanel', 1, '2025-06-01', 'Done', 9),
('Migration cloud', 'Déplacement vers Google Cloud', 3, '2025-07-15', 'In Progress', 10),
('Système de notifications', 'Intégration WebSocket', 2, '2025-08-01', 'To Do', 11),
('Refactoring module A', 'Application principes SOLID', 4, '2025-09-10', 'In Progress', 12),
('Intégration Elasticsearch', 'Recherche full-text', 1, '2025-10-05', 'Done', 13),
('Formation clients', 'Création vidéos démo', 3, '2025-11-20', 'To Do', 14),
('Synchronisation données', 'ETL avec Apache Airflow', 2, '2025-12-01', 'In Progress', 15),
('Audit accessibilité', 'Conformité WCAG 2.1', 4, '2026-01-15', 'To Do', 16),
('Mise à jour légale', 'Conformité RGPD', 1, '2026-02-28', 'Done', 17),
('Développement plugin', 'Intégration WordPress', 3, '2026-03-10', 'In Progress', 18),
('Optimisation mémoire', 'Profilage avec YourKit', 2, '2026-04-05', 'To Do', 19),
('Gestion des secrets', 'Intégration HashiCorp Vault', 4, '2026-05-20', 'In Progress', 20),
('Revue architecture', 'Diagrammes UML et ADR', 1, '2026-06-01', 'Done', 1),
('Automatisation déploiement', 'Scripts Ansible/Terraform', 3, '2026-07-15', 'To Do', 2),
('Monitoring API', 'Configuration Swagger/OpenAPI', 2, '2026-08-01', 'In Progress', 3),
('Génération de rapports', 'Export PDF/Excel', 4, '2026-09-10', 'To Do', 4),
('Sauvegardes automatisées', 'Configuration AWS S3 Glacier', 1, '2026-10-05', 'Done', 5),
('Validation données', 'Implémentation contrôles qualité', 3, '2026-11-20', 'In Progress', 6),
('Migration UI Kit', 'Passage des Material UI à Ant Design', 2, '2026-12-01', 'To Do', 7),
('Tests de pénétration', 'Audit sécurité externe', 4, '2027-01-15', 'In Progress', 8),
('Optimisation requêtes', 'Analyse EXPLAIN PLAN', 1, '2027-02-28', 'Done', 9);

-- Administrateurs de leur propre projet (20 premiers)
INSERT INTO "project_user" ("user", "project", "role") VALUES
                                                         (1, 1, 'Administrateur'),
                                                         (2, 2, 'Administrateur'),
                                                         (3, 3, 'Administrateur'),
                                                         (4, 4, 'Administrateur'),
                                                         (5, 5, 'Administrateur'),
                                                         (6, 6, 'Administrateur'),
                                                         (7, 7, 'Administrateur'),
                                                         (8, 8, 'Administrateur'),
                                                         (9, 9, 'Administrateur'),
                                                         (10, 10, 'Administrateur'),
                                                         (11, 11, 'Administrateur'),
                                                         (12, 12, 'Administrateur'),
                                                         (13, 13, 'Administrateur'),
                                                         (14, 14, 'Administrateur'),
                                                         (15, 15, 'Administrateur'),
                                                         (16, 16, 'Administrateur'),
                                                         (17, 17, 'Administrateur'),
                                                         (18, 18, 'Administrateur'),
                                                         (19, 19, 'Administrateur'),
                                                         (20, 20, 'Administrateur');

-- Associations supplémentaires (30 entrées)
INSERT INTO "project_user" ("user", "project", "role") VALUES
-- Administrateurs (6)
(3, 5, 'Administrateur'),
(5, 3, 'Administrateur'),
(7, 10, 'Administrateur'),
(10, 7, 'Administrateur'),
(12, 15, 'Administrateur'),
(15, 12, 'Administrateur'),

-- Membres (18)
(1, 2, 'Membre'),
(2, 3, 'Membre'),
(3, 4, 'Membre'),
(4, 6, 'Membre'),
(5, 7, 'Membre'),
(6, 8, 'Membre'),
(7, 9, 'Membre'),
(8, 10, 'Membre'),
(9, 11, 'Membre'),
(10, 12, 'Membre'),
(11, 13, 'Membre'),
(12, 14, 'Membre'),
(13, 15, 'Membre'),
(14, 16, 'Membre'),
(15, 17, 'Membre'),
(16, 18, 'Membre'),
(17, 19, 'Membre'),
(18, 20, 'Membre'),

-- Observateurs (6)
(4, 5, 'Observateur'),
(5, 6, 'Observateur'),
(6, 7, 'Observateur'),
(7, 8, 'Observateur'),
(8, 9, 'Observateur'),
(9, 10, 'Observateur');
